[CmdletBinding()]
param(
    [string]$Namespace = "trainticket",
    [string]$TrainTicketRoot = "",
    [switch]$SkipInfrastructure,
    [switch]$Reset,
    [switch]$WaitReady,
    [int]$ReadyTimeoutSeconds = 900,
    # On a Linux GCP VM the bundled radondb-mysql HA chart (3 pods) starts
    # cleanly. On Docker Desktop kind the xenon HA coordinator needs
    # storage/kernel features that aren't available; in that case set
    # -LocalSmokeTest, which installs the same chart with replicaCount=1
    # and weaker probes. Suitable only for verifying the rest of the
    # pipeline, not for a real dataset collection.
    [switch]$LocalSmokeTest,
    # Skip the radondb-mysql / xenon HA scoring entirely. Use this on a
    # local kind cluster where the bundled chart doesn't survive. The
    # script still installs nacos+rabbitmq and applies the secrets/svcs,
    # so a researcher can manually drop in their own MySQL release named
    # `nacosdb-mysql-leader` / `tsdb-mysql-leader` for smoke testing.
    [switch]$SkipMysql
)

# Deploys FudanSELab/train-ticket into a Kubernetes cluster using the
# upstream Makefile-equivalent steps. The upstream `make deploy` target
# is a Bash script that expects helm/kubectl on a *nix shell; this
# wrapper reproduces the same steps in PowerShell so it runs identically
# on Windows (laptop smoke test) and the GCP Ubuntu VM (full collection).
#
# What this does:
#   1. Creates the namespace from deploy/research-lab/namespaces.yaml
#      so the observability overlay's alloy regex picks up pod logs.
#   2. Installs the three infrastructure helm charts (mysql, nacos,
#      rabbitmq) that train-ticket depends on, wiring nacos to its
#      backing MySQL the same way `hack/deploy/utils.sh` does.
#   3. Applies the secret + service manifests, then renders deploy.yaml
#      from deploy.yaml.sample and applies it.
#   4. Optionally waits for every train-ticket pod to be Ready.
#
# This matches `make deploy Namespace=trainticket` from the upstream
# repo. The upstream script does NOT pin the image tag; it relies on
# `codewisdom/ts-*` from Docker Hub.

$ErrorActionPreference = "Stop"

Import-Module (Join-Path (Join-Path $PSScriptRoot "lib") "ResearchLab.psm1") -Force

$repoRoot = Get-ResearchLabRepoRoot

if (-not $TrainTicketRoot) {
    $TrainTicketRoot = Join-ResearchLabPath @($repoRoot, "train-ticket")
}

if (-not (Test-Path -LiteralPath $TrainTicketRoot)) {
    throw "train-ticket repo not found at $TrainTicketRoot. Clone it with: git clone --depth=1 https://github.com/FudanSELab/train-ticket.git $TrainTicketRoot"
}

$localHelm = Join-ResearchLabPath @($repoRoot, ".tools", "helm.exe")
$helm = Get-Command helm -ErrorAction SilentlyContinue
if ($null -eq $helm -and (Test-Path $localHelm)) {
    $helm = $localHelm
}
if ($null -eq $helm) {
    throw "helm is not installed."
}

if (-not (Get-Command kubectl -ErrorAction SilentlyContinue)) {
    throw "kubectl is not installed."
}

# Train-ticket chart paths (relative to the train-ticket repo root).
$mysqlChart = Join-ResearchLabPath @($TrainTicketRoot, "deployment", "kubernetes-manifests", "quickstart-k8s", "charts", "mysql")
$nacosChart = Join-ResearchLabPath @($TrainTicketRoot, "deployment", "kubernetes-manifests", "quickstart-k8s", "charts", "nacos")
$rabbitmqChart = Join-ResearchLabPath @($TrainTicketRoot, "deployment", "kubernetes-manifests", "quickstart-k8s", "charts", "rabbitmq")

# Bundled YAML manifests.
$svcManifest = Join-ResearchLabPath @($TrainTicketRoot, "deployment", "kubernetes-manifests", "quickstart-k8s", "yamls", "svc.yaml")
$deploySample = Join-ResearchLabPath @($TrainTicketRoot, "deployment", "kubernetes-manifests", "quickstart-k8s", "yamls", "deploy.yaml.sample")
# secret.yaml is GENERATED by the upstream bash hack — we generate it
# in-process below.
$generatedSecret = Join-ResearchLabPath @($repoRoot, "data", "build", "trainticket-secret.yaml")

foreach ($path in @($mysqlChart, $nacosChart, $rabbitmqChart, $svcManifest, $deploySample)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Required train-ticket asset not found: $path"
    }
}

function New-TrainTicketSecretYaml {
    param(
        [Parameter(Mandatory = $true)][string]$OutputPath,
        [Parameter(Mandatory = $true)][string]$MysqlHost,
        [Parameter(Mandatory = $true)][string]$MysqlUser,
        [Parameter(Mandatory = $true)][string]$MysqlPassword,
        [Parameter(Mandatory = $true)][string]$MysqlDatabase
    )

    # Mirrors hack/deploy/gen-mysql-secret.sh::gen_secret_for_services.
    # Each train-ticket service consumes a Secret named ts-<svc>-mysql
    # with env vars <SVC>_MYSQL_{HOST,PORT,DATABASE,USER,PASSWORD}.
    $svcList = @(
        "assurance", "auth", "config", "consign-price", "consign",
        "contacts", "delivery", "food", "food-delivery", "inside-payment",
        "notification", "order-other", "order", "payment", "price",
        "route", "security", "station-food", "station", "ticket-office",
        "train-food", "train", "travel", "travel2", "user", "voucher",
        "wait-order"
    )

    $parent = Split-Path -Parent $OutputPath
    if ($parent) {
        New-ResearchLabDirectory -Path $parent
    }

    $sb = [System.Text.StringBuilder]::new()
    foreach ($svc in $svcList) {
        $upper = ($svc -replace "-", "_").ToUpperInvariant()
        $hostKey = "${upper}_MYSQL_HOST"
        $portKey = "${upper}_MYSQL_PORT"
        $dbKey   = "${upper}_MYSQL_DATABASE"
        $userKey = "${upper}_MYSQL_USER"
        $pwdKey  = "${upper}_MYSQL_PASSWORD"

        [void]$sb.AppendLine("apiVersion: v1")
        [void]$sb.AppendLine("kind: Secret")
        [void]$sb.AppendLine("metadata:")
        [void]$sb.AppendLine("  name: ts-${svc}-mysql")
        [void]$sb.AppendLine("type: Opaque")
        [void]$sb.AppendLine("stringData:")
        [void]$sb.AppendLine("  ${hostKey}: ""${MysqlHost}""")
        [void]$sb.AppendLine("  ${portKey}: ""3306""")
        [void]$sb.AppendLine("  ${dbKey}: ""${MysqlDatabase}""")
        [void]$sb.AppendLine("  ${userKey}: ""${MysqlUser}""")
        [void]$sb.AppendLine("  ${pwdKey}: ""${MysqlPassword}""")
        [void]$sb.AppendLine("---")
    }

    [System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
    return $OutputPath
}

function Invoke-HelmInstall {
    param(
        [string]$Release,
        [string]$Chart,
        [string[]]$Sets,
        [string]$NamespaceArg
    )

    # `helm status` on a non-existent release writes to stderr AND exits 1.
    # Under $ErrorActionPreference=Stop, native-command stderr would surface
    # as a NativeCommandError and crash the script. Suppress for the probe.
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & $helm status $Release -n $NamespaceArg 2>&1 | Out-Null
    } catch {
    }
    $alreadyInstalled = ($LASTEXITCODE -eq 0)
    $ErrorActionPreference = $prev
    if ($alreadyInstalled) {
        Write-Host "  helm release $Release already exists in $NamespaceArg; skipping install"
        return
    }

    $args = @("install", $Release)
    foreach ($entry in $Sets) {
        $args += @("--set", $entry)
    }
    $args += @($Chart, "-n", $NamespaceArg, "--create-namespace")

    & $helm @args
    if ($LASTEXITCODE -ne 0) {
        throw "helm install $Release failed."
    }
}

function Wait-StatefulSet {
    param(
        [string]$Name,
        [string]$NamespaceArg,
        [int]$TimeoutSec = 600
    )

    Write-Host "  waiting for statefulset/$Name to be ready ..."
    kubectl rollout status "statefulset/$Name" -n $NamespaceArg --timeout=${TimeoutSec}s
    if ($LASTEXITCODE -ne 0) {
        throw "statefulset/$Name did not become ready within ${TimeoutSec}s"
    }
}

function Wait-Deployment {
    param(
        [string]$Name,
        [string]$NamespaceArg,
        [int]$TimeoutSec = 600
    )

    Write-Host "  waiting for deployment/$Name to be ready ..."
    kubectl rollout status "deployment/$Name" -n $NamespaceArg --timeout=${TimeoutSec}s
    if ($LASTEXITCODE -ne 0) {
        throw "deployment/$Name did not become ready within ${TimeoutSec}s"
    }
}

# 0. Namespace.
kubectl apply -f (Join-ResearchLabPath @($repoRoot, "deploy", "research-lab", "namespaces.yaml"))

if ($Reset) {
    Write-Host "Reset requested. Removing existing train-ticket release ..."
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        foreach ($rel in @("nacosdb", "nacos", "rabbitmq", "tsdb")) {
            & $helm uninstall $rel -n $Namespace 2>&1 | Out-Null
        }
        kubectl delete -f $svcManifest -n $Namespace --ignore-not-found 2>&1 | Out-Null
        if (Test-Path -LiteralPath $generatedSecret) {
            kubectl delete -f $generatedSecret -n $Namespace --ignore-not-found 2>&1 | Out-Null
        }
        kubectl delete deployment --all -n $Namespace --ignore-not-found 2>&1 | Out-Null
        kubectl delete pvc --all -n $Namespace --ignore-not-found 2>&1 | Out-Null
    } finally {
        $ErrorActionPreference = $prev
    }
}

# 1. Infrastructure: nacos MySQL, nacos server, rabbitmq, train-ticket MySQL.
$nacosDBUser = "nacos"
$nacosDBPass = "Abcd1234#"
$nacosDBName = "nacos"
$tsUser = "ts"
$tsPass = "Ts_123456"
$tsDB = "ts"

if (-not $SkipInfrastructure) {
    Write-Host "Step 1/3: train-ticket infrastructure (mysql + nacos + rabbitmq + ts-mysql)"

    $mysqlSets = @()
    if ($LocalSmokeTest) {
        # Single-replica radondb-mysql for local kind smoke tests. The chart
        # comment says not to change replicaCount after first install, but
        # we're installing fresh. We also loosen liveness probes so the
        # initial xenon bootstrap doesn't get killed by 30s probe windows.
        $mysqlSets = @(
            "replicaCount=1",
            "mysql.livenessProbe.initialDelaySeconds=120",
            "mysql.readinessProbe.initialDelaySeconds=60"
        )
        Write-Host "  -LocalSmokeTest: requesting replicaCount=1 with relaxed probes."
    }

    if (-not $SkipMysql) {
        Invoke-HelmInstall -Release "nacosdb" -Chart $mysqlChart -NamespaceArg $Namespace -Sets ($mysqlSets + @(
            "mysql.mysqlUser=$nacosDBUser",
            "mysql.mysqlPassword=$nacosDBPass",
            "mysql.mysqlDatabase=$nacosDBName"
        ))
        Wait-StatefulSet -Name "nacosdb-mysql" -NamespaceArg $Namespace
    }

    Invoke-HelmInstall -Release "nacos" -Chart $nacosChart -NamespaceArg $Namespace -Sets @(
        "nacos.db.host=nacosdb-mysql-leader",
        "nacos.db.username=$nacosDBUser",
        "nacos.db.name=$nacosDBName",
        "nacos.db.password=$nacosDBPass"
    )
    Wait-StatefulSet -Name "nacos" -NamespaceArg $Namespace

    Invoke-HelmInstall -Release "rabbitmq" -Chart $rabbitmqChart -NamespaceArg $Namespace -Sets @()
    Wait-Deployment -Name "rabbitmq" -NamespaceArg $Namespace

    if (-not $SkipMysql) {
        Invoke-HelmInstall -Release "tsdb" -Chart $mysqlChart -NamespaceArg $Namespace -Sets ($mysqlSets + @(
            "mysql.mysqlUser=$tsUser",
            "mysql.mysqlPassword=$tsPass",
            "mysql.mysqlDatabase=$tsDB"
        ))
        Wait-StatefulSet -Name "tsdb-mysql" -NamespaceArg $Namespace
    }
}

# 2. MySQL connection secret for train-ticket services. The upstream
# `gen-mysql-secret.sh` writes a Secret per service that points every
# service at the all-in-one MySQL host (tsdb-mysql-leader). We render
# the same shape into data/build/ and apply it.
$secretPath = New-TrainTicketSecretYaml `
    -OutputPath $generatedSecret `
    -MysqlHost "tsdb-mysql-leader" `
    -MysqlUser $tsUser `
    -MysqlPassword $tsPass `
    -MysqlDatabase $tsDB
kubectl apply -f $secretPath -n $Namespace

# 3. Services + deployments.
Write-Host "Step 2/3: train-ticket services"
kubectl apply -f $svcManifest -n $Namespace

Write-Host "Step 3/3: train-ticket deployments"
# deploy.yaml.sample uses NODE_IP/NACOS/RABBITMQ envFrom configmap. We
# render the sample by injecting the `nacos` and `rabbitmq` configmaps
# generated by the upstream helm chart. Apply as-is; upstream `hack/deploy/utils.sh`
# does `update_tt_dp_cm` then `kubectl apply` of deploy.yaml. The configmap
# names in the sample (`nacos`) match the helm release name, so as long as
# the release is named `nacos` the envFrom resolves correctly.
kubectl apply -f $deploySample -n $Namespace

if ($WaitReady) {
    Write-Host "Waiting up to ${ReadyTimeoutSeconds}s for all train-ticket pods to be Ready ..."
    kubectl wait --for=condition=Ready pods --all -n $Namespace --timeout=${ReadyTimeoutSeconds}s
}

Write-Host ""
Write-Host "train-ticket deployment applied to namespace '$Namespace'."
Write-Host "Inspect status:"
Write-Host "  kubectl get pods -n $Namespace"
Write-Host "Reach the UI (NodePort 32677):"
Write-Host "  kubectl port-forward -n $Namespace svc/ts-ui-dashboard 32677:8080"
