"""TIMELINE schema — typed view of a humanized Jira ticket as a sequence
of (persona, timestamp, evidence-slice, contribution) tuples.

See LLM-Jira-enhancement.md §2 for the design rationale. The shape here
intentionally mirrors the dict layout of `jira_shadow_issues.jsonl` for
the legacy generator so downstream code can read both — `as_legacy_ticket()`
flattens the timeline into `{summary, description, comments[], resolution_notes}`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# Closed enumeration of timeline step kinds — used as a discriminator
# when the generator selects which prompt template to invoke.
class StepKind:
    REPORT = "report"            # Maps to summary + opening description
    ACK = "ack"                  # First "on it" comment
    HYPOTHESIS = "hypothesis"    # Investigation comment (may be correct OR wrong)
    REDIRECT = "redirect"        # Senior corrects misattribution
    NUDGE = "nudge"              # eng-mgr status check
    RESOLVE = "resolve"          # Resolution + close note


# What was visible to the persona when their contribution was generated.
# The generator captures this so we can later audit "did the LLM only
# see what the persona could see?".
@dataclass
class EvidenceSlice:
    log_quotes: list[str] = field(default_factory=list)
    metric_observations: list[str] = field(default_factory=list)
    k8s_observations: list[str] = field(default_factory=list)
    time_window_start: str = ""   # ISO ts (offset from episode start)
    time_window_end: str = ""     # ISO ts


@dataclass
class TimelineStep:
    """One contribution to the ticket — generated by one LLM call.

    The (persona_role, persona_avatar) split is intentional: many
    `oncall-sre` contributions across the corpus should share the role
    but rotate avatars so the model can't memorize "Sarah Chen always
    handles cart-redis tickets".
    """

    step_kind: str            # one of StepKind.*
    persona_role: str         # e.g. "oncall-sre", "cs-agent"
    persona_avatar: str       # e.g. "Sarah Chen"
    t_offset_s: int           # seconds since episode start
    context_window_s: int     # how much of the fault was visible to this persona
    evidence: EvidenceSlice
    text: str = ""            # the actual contribution (LLM output)
    # The generator records the prompt hash so re-runs can be
    # deterministically diffed against original outputs.
    prompt_hash: str = ""


@dataclass
class TicketTimeline:
    """A ticket as an ordered timeline of contributions.

    Carries provenance fields (`source_episode_id`, `generator_version`)
    so the global Jira memory corpus can join timeline → episode → window
    without re-reading the legacy generator's manifest.

    Layout invariant: `steps[0].step_kind == StepKind.REPORT` and the
    last step is REPORT-or-RESOLVE — there's always a report and (if
    the ticket closes) a resolve.
    """

    ticket_id: str
    source_episode_id: str
    source_dataset_run_id: str
    affected_services_seen: list[str]
    severity_seen: str           # the SYMPTOM severity the reporter would assign
    components_seen: list[str]   # may be deliberately wrong — see Rule 3
    is_misattributed: bool       # True if components_seen disagrees with truth
    closed_as_noise: bool        # True if Rule 5 close-as-noise was sampled
    steps: list[TimelineStep] = field(default_factory=list)
    generator_version: str = ""
    sanitizer_version: str = ""
    symptom_map_version: str = ""

    def as_legacy_ticket(self) -> dict[str, Any]:
        """Flatten to the legacy jira_shadow_issues.jsonl shape.

        Used by pipelines that haven't been updated to read TIMELINE
        natively yet. The first REPORT step's text becomes the
        description; subsequent steps become comments; the final
        RESOLVE (if present) populates resolution_notes.
        """
        if not self.steps:
            return {"summary": "", "description": "", "comments": [], "resolution_notes": ""}

        report = self.steps[0]
        comments = []
        resolution = ""
        for step in self.steps[1:]:
            if step.step_kind == StepKind.RESOLVE:
                resolution = step.text
                # Resolve also reads as the last comment in the comment thread.
                comments.append({
                    "author": step.persona_avatar,
                    "role": step.persona_role,
                    "t_offset_s": step.t_offset_s,
                    "body": step.text,
                })
            else:
                comments.append({
                    "author": step.persona_avatar,
                    "role": step.persona_role,
                    "t_offset_s": step.t_offset_s,
                    "body": step.text,
                })

        return {
            "summary": _first_line(report.text),
            "description": report.text,
            "comments": comments,
            "resolution_notes": resolution,
            "reporter": report.persona_avatar,
            "reporter_role": report.persona_role,
            "affected_services": self.affected_services_seen,
            "components": self.components_seen,
            "severity": self.severity_seen,
            "closed_as_noise": self.closed_as_noise,
            "is_misattributed": self.is_misattributed,
        }

    def as_jsonl_row(self) -> dict[str, Any]:
        """Self-describing dict for timeline.jsonl. Use for the new
        humanized corpus; the legacy view is for back-compat only."""
        return {
            "ticket_id": self.ticket_id,
            "source_episode_id": self.source_episode_id,
            "source_dataset_run_id": self.source_dataset_run_id,
            "affected_services_seen": self.affected_services_seen,
            "severity_seen": self.severity_seen,
            "components_seen": self.components_seen,
            "is_misattributed": self.is_misattributed,
            "closed_as_noise": self.closed_as_noise,
            "generator_version": self.generator_version,
            "sanitizer_version": self.sanitizer_version,
            "symptom_map_version": self.symptom_map_version,
            "timeline": [
                {
                    "step_kind": s.step_kind,
                    "persona_role": s.persona_role,
                    "persona_avatar": s.persona_avatar,
                    "t_offset_s": s.t_offset_s,
                    "context_window_s": s.context_window_s,
                    "evidence": {
                        "log_quotes": s.evidence.log_quotes,
                        "metric_observations": s.evidence.metric_observations,
                        "k8s_observations": s.evidence.k8s_observations,
                        "time_window_start": s.evidence.time_window_start,
                        "time_window_end": s.evidence.time_window_end,
                    },
                    "text": s.text,
                    "prompt_hash": s.prompt_hash,
                }
                for s in self.steps
            ],
        }


def _first_line(text: str) -> str:
    """The summary is the first non-empty line of the report contribution.
    Capped at ~140 chars so it actually fits in a Jira summary field."""
    for line in (text or "").splitlines():
        line = line.strip()
        if line:
            return line[:140]
    return ""
