"""TIMELINE schema — typed view of a humanized Jira ticket as a sequence
of (persona, timestamp, evidence-slice, contribution) tuples.

See LLM-Jira-enhancement.md §2 for the design rationale. The shape here
intentionally mirrors the dict layout of `jira_shadow_issues.jsonl` for
the legacy generator so downstream code can read both — `as_legacy_ticket()`
flattens the timeline into `{summary, description, comments[], resolution_notes}`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# Closed enumeration of timeline step kinds — used as a discriminator
# when the generator selects which prompt template to invoke.
class StepKind:
    REPORT = "report"            # Maps to summary + opening description
    ACK = "ack"                  # First "on it" comment
    HYPOTHESIS = "hypothesis"    # Investigation comment (may be correct OR wrong)
    REDIRECT = "redirect"        # Senior corrects misattribution
    NUDGE = "nudge"              # eng-mgr status check
    RESOLVE = "resolve"          # Resolution + close note


# What was visible to the persona when their contribution was generated.
# The generator captures this so we can later audit "did the LLM only
# see what the persona could see?".
# V2 extension (§13.12): multi-channel evidence — logs + metrics + trace
# + k8s + alerts. All fields are pre-sanitized strings. The dict-typed
# trace_summary / k8s_state from EvidenceBundle are flattened to lists
# of engineer-readable strings here so the jsonl schema stays uniform.
@dataclass
class EvidenceSlice:
    log_quotes: list[str] = field(default_factory=list)
    metric_observations: list[str] = field(default_factory=list)
    k8s_observations: list[str] = field(default_factory=list)
    # V2 additions
    trace_observations: list[str] = field(default_factory=list)
    alert_names: list[str] = field(default_factory=list)
    trace_id_quoted: str | None = None
    symptom_phrase: str = ""
    time_window_start: str = ""   # ISO ts (offset from episode start)
    time_window_end: str = ""     # ISO ts


@dataclass
class TimelineStep:
    """One contribution to the ticket — generated by one LLM call.

    The (persona_role, persona_avatar) split is intentional: many
    `oncall-sre` contributions across the corpus should share the role
    but rotate avatars so the model can't memorize "Sarah Chen always
    handles cart-redis tickets".
    """

    step_kind: str            # one of StepKind.*
    persona_role: str         # e.g. "oncall-sre", "cs-agent"
    persona_avatar: str       # e.g. "Sarah Chen"
    t_offset_s: int           # seconds since episode start
    context_window_s: int     # how much of the fault was visible to this persona
    evidence: EvidenceSlice
    text: str = ""            # the prose contribution (LLM output)
    # V2 — Comment_Code analog per §13.2. Raw log lines this persona pasted
    # alongside their prose, drawn from `evidence.log_quotes` for the step.
    # None when this step's persona doesn't naturally paste logs
    # (e.g. cs-agent, eng-mgr) or when no log lines were available.
    body_code: str | None = None
    # The generator records the prompt hash so re-runs can be
    # deterministically diffed against original outputs.
    prompt_hash: str = ""


@dataclass
class TicketTimeline:
    """A ticket as an ordered timeline of contributions.

    Carries provenance fields (`source_episode_id`, `generator_version`)
    so the global Jira memory corpus can join timeline → episode → window
    without re-reading the legacy generator's manifest.

    Layout invariant: `steps[0].step_kind == StepKind.REPORT` and the
    last step is REPORT-or-RESOLVE — there's always a report and (if
    the ticket closes) a resolve.
    """

    ticket_id: str
    source_episode_id: str
    source_dataset_run_id: str
    affected_services_seen: list[str]
    severity_seen: str           # the SYMPTOM severity the reporter would assign
    components_seen: list[str]   # may be deliberately wrong — see Rule 3
    is_misattributed: bool       # True if components_seen disagrees with truth
    closed_as_noise: bool        # True if Rule 5 close-as-noise was sampled
    steps: list[TimelineStep] = field(default_factory=list)
    generator_version: str = ""
    sanitizer_version: str = ""
    symptom_map_version: str = ""
    # ---- V2 additions per §13.2 ----
    # Description_Code analog — characteristic log lines from Move A,
    # joined with newlines. Empty allowed per §13.3 rule 3c.
    description_code: str = ""
    # Resolution outcome (Fixed / Won't Fix / Duplicate / Cannot Reproduce /
    # Not A Bug / Timed out). V1 kept everything as Fixed; V2 samples per
    # §13.1. Empty string = use the V1 default ("Fixed").
    resolution: str = ""
    # Sampled per §13.1 distribution; 0 = unknown (V1 didn't track this).
    resolution_time_s: int = 0
    # §13.5 — distractor tickets evaluate retrieval precision.
    is_distractor: bool = False
    # §13.9 #3 — parent ticket_id when this is a critical-severity followup.
    is_followup_of: str | None = None
    # Provenance back to the injection that produced this ticket. None for
    # distractors and baseline tickets.
    source_injection_id: str | None = None
    # Captures signature_for_episode() source: "diff" | "plain_fallback" | "empty"
    log_signature_source: str = ""
    # sha256[:16] of the canonical EvidenceBundle that drove generation —
    # reproducibility per §12.
    evidence_bundle_hash: str = ""

    def as_legacy_ticket(self) -> dict[str, Any]:
        """Flatten to the legacy jira_shadow_issues.jsonl shape.

        Used by pipelines that haven't been updated to read TIMELINE
        natively yet. The first REPORT step's text becomes the
        description; subsequent steps become comments; the final
        RESOLVE (if present) populates resolution_notes.

        V2: comments carry `body_code` alongside `body` so downstream
        readers that index pasted log content get a stable channel for
        BM25-on-engineer-vocabulary retrieval.
        """
        if not self.steps:
            return {"summary": "", "description": "", "comments": [], "resolution_notes": ""}

        report = self.steps[0]
        comments = []
        resolution = ""
        for step in self.steps[1:]:
            comments.append({
                "author": step.persona_avatar,
                "role": step.persona_role,
                "t_offset_s": step.t_offset_s,
                "body": step.text,
                "body_code": step.body_code,
            })
            if step.step_kind == StepKind.RESOLVE:
                resolution = step.text

        # V2 description is prose-only and short (§13.3). The full text
        # the LLM produced is still available on report.text; the
        # `description` field here is the capped surface for downstream
        # readers that expect short descriptions.
        return {
            "summary": _first_line(report.text),
            "description": _cap_description(report.text),
            "description_code": self.description_code,
            "comments": comments,
            "resolution": self.resolution or ("Fixed" if not self.closed_as_noise else "Won't Fix"),
            "resolution_notes": resolution,
            "resolution_time_s": self.resolution_time_s,
            "reporter": report.persona_avatar,
            "reporter_role": report.persona_role,
            "affected_services": self.affected_services_seen,
            "components": self.components_seen,
            "severity": self.severity_seen,
            "closed_as_noise": self.closed_as_noise,
            "is_misattributed": self.is_misattributed,
            "is_distractor": self.is_distractor,
            "is_followup_of": self.is_followup_of,
        }

    def as_jsonl_row(self) -> dict[str, Any]:
        """Self-describing dict for timeline.jsonl. Use for the new
        humanized corpus; the legacy view is for back-compat only."""
        return {
            "ticket_id": self.ticket_id,
            "source_episode_id": self.source_episode_id,
            "source_dataset_run_id": self.source_dataset_run_id,
            "source_injection_id": self.source_injection_id,
            "affected_services_seen": self.affected_services_seen,
            "severity_seen": self.severity_seen,
            "components_seen": self.components_seen,
            "is_misattributed": self.is_misattributed,
            "closed_as_noise": self.closed_as_noise,
            "is_distractor": self.is_distractor,
            "is_followup_of": self.is_followup_of,
            "description_code": self.description_code,
            "resolution": self.resolution,
            "resolution_time_s": self.resolution_time_s,
            "log_signature_source": self.log_signature_source,
            "evidence_bundle_hash": self.evidence_bundle_hash,
            "generator_version": self.generator_version,
            "sanitizer_version": self.sanitizer_version,
            "symptom_map_version": self.symptom_map_version,
            "timeline": [
                {
                    "step_kind": s.step_kind,
                    "persona_role": s.persona_role,
                    "persona_avatar": s.persona_avatar,
                    "t_offset_s": s.t_offset_s,
                    "context_window_s": s.context_window_s,
                    "evidence": {
                        "log_quotes": s.evidence.log_quotes,
                        "metric_observations": s.evidence.metric_observations,
                        "k8s_observations": s.evidence.k8s_observations,
                        "trace_observations": s.evidence.trace_observations,
                        "alert_names": s.evidence.alert_names,
                        "trace_id_quoted": s.evidence.trace_id_quoted,
                        "symptom_phrase": s.evidence.symptom_phrase,
                        "time_window_start": s.evidence.time_window_start,
                        "time_window_end": s.evidence.time_window_end,
                    },
                    "text": s.text,
                    "body_code": s.body_code,
                    "prompt_hash": s.prompt_hash,
                }
                for s in self.steps
            ],
        }


# V2 — short prose description per §13.3 / §13.1 (TAWOS median 200-500 chars).
# Hard cap; LLM is also steered toward short prose via the persona prompt.
DESCRIPTION_MAX_CHARS = 500


def _cap_description(text: str) -> str:
    """Cap the report-step text at DESCRIPTION_MAX_CHARS. Tries to break
    on a sentence boundary near the cap so we don't slice mid-word."""
    s = (text or "").strip()
    if len(s) <= DESCRIPTION_MAX_CHARS:
        return s
    # Look for a sentence end in the last ~80 chars before the cap.
    window_start = max(0, DESCRIPTION_MAX_CHARS - 80)
    for end_char in (". ", "! ", "? ", "\n"):
        idx = s.rfind(end_char, window_start, DESCRIPTION_MAX_CHARS)
        if idx != -1:
            return s[: idx + 1].rstrip()
    # No sentence boundary nearby — hard cut + ellipsis.
    return s[: DESCRIPTION_MAX_CHARS].rstrip() + "..."


def _first_line(text: str) -> str:
    """The summary is the first non-empty line of the report contribution.
    Capped at ~140 chars so it actually fits in a Jira summary field."""
    for line in (text or "").splitlines():
        line = line.strip()
        if line:
            return line[:140]
    return ""
