"""Loader + iter_split equivalent for the window-level (v2) manifest.

The v1 `iter_split(windows, manifest, split)` consults the family→split
table. For v2 we consult a window_id→split table instead. Same return
contract, drop-in usable wherever v1 iter_split is used.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from loganalyzer.data.schema import TriageWindow

from v2_advanced.shared import get_logger

log = get_logger("phase_a.window_split")


@dataclass
class WindowSplitManifest:
    """Window-level split manifest.

    Loaded from a JSON file generated by `make_resplit.py`. Provides
    `split_of(window_id) -> "train"|"validation"|"test"`.
    """

    window_assignment: dict[str, str]
    global_dataset_id: str
    seed: int
    leave_one_family_out_folds: list[str]
    split_by: str = "window_id"

    @classmethod
    def from_path(cls, path: Path) -> "WindowSplitManifest":
        row = json.loads(path.read_text(encoding="utf-8"))
        if row.get("split_by") != "window_id":
            raise ValueError(
                f"manifest at {path} has split_by={row.get('split_by')}; "
                "expected 'window_id' for v2 in-distribution split"
            )
        return cls(
            window_assignment=row["window_assignment"],
            global_dataset_id=row.get("global_dataset_id", ""),
            seed=row.get("seed", 42),
            leave_one_family_out_folds=row.get("leave_one_family_out_folds", []),
        )

    def split_of(self, window_id: str) -> str:
        return self.window_assignment.get(window_id, "train")


def iter_window_split(
    windows: list[TriageWindow],
    manifest: WindowSplitManifest,
    split: str,
) -> Iterator[TriageWindow]:
    """Yield only windows in the requested split."""
    for w in windows:
        if manifest.split_of(w.window_id) == split:
            yield w


def load_v2_manifest(global_dir: Path, *, filename: str = "triage-split-manifest-v2-resplit.json") -> WindowSplitManifest:
    """Load the v2 manifest file from a global dataset directory."""
    path = global_dir / filename
    if not path.exists():
        raise FileNotFoundError(
            f"v2 manifest not found at {path}; "
            "run `python -m v2_advanced.proposal_a_resplit.make_resplit ...` first"
        )
    m = WindowSplitManifest.from_path(path)
    log.info(
        "loaded v2 manifest",
        windows=len(m.window_assignment),
        seed=m.seed,
    )
    return m
