"""Smoke test: run the agent end-to-end on OTel Demo.

OTel Demo is the **second telemetry-rich dataset** (alongside OB).
As of 2026-06-12 the cascade hasn't been run on it, so the
predictions-backed retrievers have nothing to load and the smoke
test produces the empty-retrieval baseline. The point of this run
is to verify the pipeline works end-to-end so a real pass lands
cleanly once the cascade has populated `comparison/`.

Phase 2/3 upgrade: this smoke now uses the shared
`agent.harness_builder.build_harness_for_dataset` factory with
`dataset_label="otel_demo"` — the SAME wiring as smoke_ob and
smoke_wol, only the per-dataset profile changes. The 4 ReAct
EvidenceRequestSkills, RerankWithEvidenceSkill, and
ReformulateQuerySkill are all registered automatically.

Splits come from `triage-split-manifest-v2-resplit.json` if present
(generated by `make_resplit.py`); otherwise from
`triage-split-manifest.json`. Default split is "test" — 247 windows
out of 1643 when the cut is final.

Usage:
    PYTHONPATH=src python scripts/agent/smoke_otel_demo.py \\
        --global-dir data/derived/global/2026-06-09-otel-demo-v1-global \\
        [--split test|validation|train] \\
        [--limit 100] [--output data/agent_runs/otel-smoke.json]

If the cascade hasn't been run yet, the predictions-backed
retrievers log warnings and skip themselves; the harness still
runs but retrieval metrics are all 0.0 by construction. Run the
cascade and re-invoke for real numbers.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from agent.data_loaders import load_otel_demo_cases
from agent.harness_builder import build_harness_for_dataset


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--global-dir", type=Path, required=True)
    p.add_argument("--split", default="test",
                   choices=["train", "validation", "test"])
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--cache-dir", type=Path, default=None,
                   help="SkillCache root.")
    p.add_argument("--trace-root", type=Path, default=None,
                   help="Persist per-window traces.")
    p.add_argument("--output", type=Path, default=None)
    p.add_argument("--include-verifier", action="store_true",
                   help="register verify_with_llm (default off — OTel Demo "
                        "verifier calibration is `skip` pending RQ-B1)")
    p.add_argument("--no-state", action="store_true")
    p.add_argument("--skip-skill", action="append", default=[], metavar="NAME")
    p.add_argument("--order-by-incident-time", action="store_true",
                   help="sort cases by (service, episode, start_time) so "
                        "the StateLayer sees multi-window incident sequences "
                        "(closes RQ-C7 page-suppression)")
    p.add_argument("--max-tool-calls", type=int, default=None,
                   help="RQ-A7: cap per-window ReAct tool invocations.")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    print(f"[smoke_otel] loading cases from {args.global_dir} (split={args.split})")
    cases = load_otel_demo_cases(
        args.global_dir, split=args.split, limit=args.limit,
        order_by_incident_time=args.order_by_incident_time,
    )
    print(f"[smoke_otel] loaded {len(cases)} cases")

    harness, contract = build_harness_for_dataset(
        dataset_label="otel_demo",
        global_dir=args.global_dir,
        cache_dir=args.cache_dir,
        trace_root=args.trace_root,
        skip=set(args.skip_skill),
        include_verifier=args.include_verifier,
        use_state_layer=not args.no_state,
        max_tool_calls=args.max_tool_calls,
        experiment_prefix="smoke",
    )

    print(f"[smoke_otel] running agent over {len(cases)} cases...")
    report = harness.evaluate(
        cases, contract=contract,
        experiment_name=f"otel-smoke-{args.global_dir.name}",
    )

    print()
    print("=" * 70)
    print(f"  Agent smoke test (OTel Demo) - {args.global_dir.name}")
    print("=" * 70)
    print(f"  n_cases (total):                {report.n_cases}")
    print(f"  n_cases (with retrieval gold):  {report.n_evaluable_retrieval_cases}")
    print(f"  Hit@1                           {report.hit_at_1:.4f}")
    print(f"  Hit@5                           {report.hit_at_5:.4f}")
    print(f"  Hit@10                          {report.hit_at_10:.4f}")
    print(f"  MRR                             {report.mrr:.4f}")
    print(f"  Triage accuracy                 {report.triage_accuracy:.4f}")
    print(f"  Pages emitted                   {report.n_pages_emitted}")
    print(f"  Incidents                       {report.n_incidents}")
    print(f"  Pages-per-incident              {report.pages_per_incident:.3f}")
    print(f"  Suppressions fired              {report.n_suppressions_fired}")
    print(f"  Distinct plan IDs               {len(report.plan_ids_seen)}")
    print(f"  evaluation_mode                 {report.contract.evaluation_mode}")
    print("=" * 70)

    n_retrievers = sum(
        1 for n in harness.runner.registry.names()
        if n.startswith("retrieve_") or n == "triage_numeric"
    )
    if n_retrievers == 0:
        print("  NOTE: no retriever skills registered (cascade not yet run on")
        print("        this dataset). Retrieval metrics are all 0.0 by")
        print("        construction; run the cascade and re-run for real numbers.")

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        report.write_to(args.output, include_case_results=True)
        print(f"[smoke_otel] wrote report -> {args.output}")


if __name__ == "__main__":
    main()
