"""Smoke test: run the agent end-to-end on OTel Demo.

OTel Demo is the **second telemetry-rich dataset** (alongside OB).
As of 2026-06-12 the cascade hasn't been run on it yet, so the
predictions-backed retrievers have nothing to load and the smoke
test produces the empty-retrieval baseline. The point of this run is
to verify the pipeline works end-to-end so a real pass lands cleanly
once the cascade has populated `comparison/`.

Splits come from `triage-split-manifest-v2-resplit.json` (generated by
`make_resplit.py`). Default split is "test" — 247 windows out of 1643.

Usage:
    PYTHONPATH=src python scripts/agent/smoke_otel_demo.py \\
        --global-dir data/derived/global/2026-06-09-otel-demo-v1-global \\
        [--split test|validation|train] \\
        [--limit 100] [--output data/agent_runs/otel-smoke.json]
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from agent.capabilities_observer import CapabilitiesObserver, ObservationContext
from agent.controller import RuleController
from agent.data_loaders import load_otel_demo_cases
from agent.eval_harness import ApplesToApplesContract, EvalHarness
from agent.runner import AgentRunner
from agent.skills import (
    ComposeL2Skill,
    ComposeNoveltySkill,
    ComposeTriageSkill,
    RetrieveDenseSkill,
    RetrieveHybridFusionSkill,
    SkillRegistry,
    TriageNumericSkill,
)
from agent.state import StateLayer


def _build_registry(global_dir: Path) -> SkillRegistry:
    """Build whatever predictions are available. Cascade hasn't run on
    OTel Demo yet, so most retrievers will have nothing to register;
    that's expected for the v1 smoke."""
    reg = SkillRegistry()
    comparison = global_dir / "comparison"

    for cls, subdir in [
        (TriageNumericSkill, "v2a-resplit"),
        (RetrieveDenseSkill,  "v2a-resplit"),
        (RetrieveHybridFusionSkill, "v2c-hybrid"),
    ]:
        p = comparison / subdir / "per-window-predictions.jsonl"
        if not p.exists():
            logging.warning(
                "skipping %s — cascade output missing at %s",
                cls.name, p,
            )
            continue
        reg.register(cls(predictions_path=p))

    # Composition skills are pure trace-readers; no JSONL needed.
    for cls in (ComposeL2Skill, ComposeTriageSkill, ComposeNoveltySkill):
        reg.register(cls())
    return reg


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--global-dir", type=Path, required=True)
    p.add_argument("--split", default="test", choices=["train", "validation", "test"])
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--output", type=Path, default=None)
    p.add_argument("--order-by-incident-time", action="store_true",
                   help="sort cases by (service, episode, start_time) so "
                        "the StateLayer sees multi-window incident sequences "
                        "(closes RQ-C7 page-suppression)")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    print(f"[smoke_otel] loading cases from {args.global_dir} (split={args.split})")
    cases = load_otel_demo_cases(
        args.global_dir, split=args.split, limit=args.limit,
        order_by_incident_time=args.order_by_incident_time,
    )
    print(f"[smoke_otel] loaded {len(cases)} cases")

    dataset_id = args.global_dir.name
    registry = _build_registry(args.global_dir)
    runner = AgentRunner(registry, experiment=f"smoke:{dataset_id}")
    controller = RuleController(registry)

    harness = EvalHarness(
        controller=controller, runner=runner,
        observer=CapabilitiesObserver(),
        observation_ctx=ObservationContext(
            dataset_id=dataset_id, has_memory_text=True,
        ),
        state_layer=StateLayer(),
    )
    contract = ApplesToApplesContract(
        dataset_id=dataset_id, split=args.split,
        gold_relation="coarse",
        evaluation_mode="telemetry_diagnosis",
    )

    print(f"[smoke_otel] running agent over {len(cases)} cases...")
    report = harness.evaluate(
        cases, contract=contract,
        experiment_name=f"otel-smoke-{dataset_id}",
    )

    print()
    print("=" * 70)
    print(f"  Agent smoke test (OTel Demo) - {dataset_id}")
    print("=" * 70)
    print(f"  n_cases (total):                {report.n_cases}")
    print(f"  n_cases (with retrieval gold):  {report.n_evaluable_retrieval_cases}")
    print(f"  Hit@1                           {report.hit_at_1:.4f}")
    print(f"  Hit@5                           {report.hit_at_5:.4f}")
    print(f"  Hit@10                          {report.hit_at_10:.4f}")
    print(f"  MRR                             {report.mrr:.4f}")
    print(f"  Triage accuracy                 {report.triage_accuracy:.4f}")
    print(f"  Pages emitted                   {report.n_pages_emitted}")
    print(f"  Incidents                       {report.n_incidents}")
    print(f"  Pages-per-incident              {report.pages_per_incident:.3f}")
    print(f"  Suppressions fired              {report.n_suppressions_fired}")
    print(f"  evaluation_mode                 {report.contract.evaluation_mode}")
    print("=" * 70)
    if not registry.names() or all(n.startswith("compose") for n in registry.names()):
        print("  NOTE: no retriever skills registered (cascade not yet run on")
        print("        this dataset). Retrieval metrics are all 0.0 by")
        print("        construction; run the cascade and re-run for real numbers.")

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        report.write_to(args.output, include_case_results=True)
        print(f"[smoke_otel] wrote report -> {args.output}")


if __name__ == "__main__":
    main()
